export const countries = [
  { code: 'TR', name: 'Turkey', label: 'Türkiye' },
  { code: 'IT', name: 'Italy', label: 'İtalya' },
  { code: 'FR', name: 'France', label: 'Fransa' },
  { code: 'ES', name: 'Spain', label: 'İspanya' },
  { code: 'GR', name: 'Greece', label: 'Yunanistan' },
  { code: 'PT', name: 'Portugal', label: 'Portekiz' },
  { code: 'GB', name: 'United Kingdom', label: 'Birleşik Krallık' },
  { code: 'DE', name: 'Germany', label: 'Almanya' },
  { code: 'NL', name: 'Netherlands', label: 'Hollanda' },
  { code: 'BE', name: 'Belgium', label: 'Belçika' },
  { code: 'CH', name: 'Switzerland', label: 'İsviçre' },
  { code: 'AT', name: 'Austria', label: 'Avusturya' },
  { code: 'CZ', name: 'Czechia', label: 'Çekya' },
  { code: 'HU', name: 'Hungary', label: 'Macaristan' },
  { code: 'HR', name: 'Croatia', label: 'Hırvatistan' },
  { code: 'RS', name: 'Serbia', label: 'Sırbistan' },
  { code: 'AL', name: 'Albania', label: 'Arnavutluk' },
  { code: 'ME', name: 'Montenegro', label: 'Karadağ' },
  { code: 'MA', name: 'Morocco', label: 'Fas' },
  { code: 'EG', name: 'Egypt', label: 'Mısır' },
  { code: 'AE', name: 'United Arab Emirates', label: 'Birleşik Arap Emirlikleri' },
  { code: 'TH', name: 'Thailand', label: 'Tayland' },
  { code: 'JP', name: 'Japan', label: 'Japonya' },
  { code: 'KR', name: 'South Korea', label: 'Güney Kore' },
  { code: 'ID', name: 'Indonesia', label: 'Endonezya' },
  { code: 'SG', name: 'Singapore', label: 'Singapur' },
  { code: 'IN', name: 'India', label: 'Hindistan' },
  { code: 'US', name: 'United States', label: 'Amerika Birleşik Devletleri' },
  { code: 'CA', name: 'Canada', label: 'Kanada' },
  { code: 'MX', name: 'Mexico', label: 'Meksika' },
  { code: 'BR', name: 'Brazil', label: 'Brezilya' },
  { code: 'AR', name: 'Argentina', label: 'Arjantin' },
  { code: 'AU', name: 'Australia', label: 'Avustralya' },
  { code: 'NZ', name: 'New Zealand', label: 'Yeni Zelanda' },
] as const;

export function getCountry(code: string) {
  return countries.find((country) => country.code === code.toUpperCase());
}
