export { palette } from '../../theme/tokens';

export const styles = {
  page: 'flex-1 bg-[#F8F7F2]',
  content: 'px-5 pb-[23px]',
  row: 'flex-row items-center gap-[7px]',
  between: 'flex-row items-center justify-between gap-2',
  title: 'font-garamond text-[31px] text-[#203E35]',
  text: 'font-manrope text-[11px] leading-[19px] text-[#203E35]',
  small: 'font-manrope text-[9px] leading-[15px] text-[#8B9389]',
  label: 'font-manrope-semibold text-[7px] tracking-[1.1px] text-[#8B9389]',
  header: 'border-b border-b-[#E7E8DF] py-3',
  icon: 'h-9 w-[34px] items-center justify-center rounded-[18px]',
  avatar: 'h-[29px] w-[29px] items-center justify-center rounded-[15px] bg-[#E1DFCB]',
  button: 'flex-row items-center gap-[5px] rounded-[20px] bg-[#203E35] px-[13px] py-[10px]',
  buttonText: 'font-manrope-semibold text-[10px] text-white',
  intro: 'items-start pb-5 pt-6',
  stats: 'flex-row gap-1 rounded-[17px] bg-[#F0F0E8] py-[17px]',
  stat: 'flex-1 items-center gap-[5px]',
  statNumber: 'font-manrope-semibold text-[16px] text-[#203E35]',
  chip: 'mr-[6px] rounded-[20px] bg-[#EEEFE7] px-[13px] py-[9px]',
  chipText: 'font-manrope-semibold text-[10px] text-[#203E35]',
  search:
    'mb-[15px] rounded-xl border border-[#E7E8DF] bg-white p-3 font-manrope text-[12px] text-[#203E35]',
  card: 'mb-[18px] rounded-[17px] border border-[#ECEDE5] bg-[#FFFDF9] p-[17px]',
  dot: 'h-[5px] w-[5px] rounded-[3px] bg-[#BD7C61]',
  cardTitle: 'mb-[11px] mt-[13px] font-garamond text-[26px] leading-[28px] text-[#203E35]',
  cardText: 'font-manrope text-[11px] leading-5 text-[#66756A]',
  photos: 'mt-[15px] flex-row gap-2',
  photo: 'h-[140px] flex-1 overflow-hidden rounded-[9px] bg-[#E4E4D6]',
  image: 'h-full w-full',
  photoCount: 'absolute bottom-[7px] right-[7px] rounded-[4px] bg-[#FFFCED] px-[5px] py-[2px]',
  recipe: 'mt-[15px] flex-row items-center gap-[10px] rounded-xl bg-[#F0F0E7] p-[10px]',
  cardFooter: 'mt-[15px] border-t border-t-[#F0F0E8] pt-[10px]',
  mood: 'flex-shrink flex-row items-center gap-[5px] rounded-xl bg-[#F4F1E6] px-[7px] py-[5px]',
  overlay: 'flex-1 justify-center bg-[#11241FF2] p-5',
  lightbox: 'h-[70%] w-full',
} as const;
