export { palette } from '../../theme/tokens';

export const styles = {
  page: 'flex-1 bg-[#F8F7F2]',
  content: 'px-5 pb-[26px]',
  row: 'flex-row items-center gap-2',
  between: 'flex-row items-center justify-between gap-2',
  title: 'font-garamond text-[27px] text-[#203E35]',
  text: 'font-manrope text-[11px] leading-[17px] text-[#203E35]',
  muted: 'font-manrope text-[10px] leading-4 text-[#8B9389]',
  label: 'font-manrope-semibold text-[8px] tracking-[1.3px] text-[#8B9389]',
  header: 'border-b border-b-[#E7E8DF] py-[13px]',
  avatar: 'h-[30px] w-[30px] items-center justify-center rounded-[15px] bg-[#DEDCC9]',
  chip: 'mr-[7px] rounded-[24px] bg-[#ECEDE5] px-[17px] py-[9px]',
  chipText: 'font-manrope-semibold text-[10px] text-[#203E35]',
  countrySelector: 'mt-[14px] rounded-[14px] bg-[#F2F4EA] px-[15px] py-3',
  countryList: 'mt-[6px] rounded-[14px] border border-[#E7E8DF] bg-[#FFFDF9] p-[10px]',
  countryOption:
    'flex-row items-center justify-between border-b border-b-[#E7E8DF] px-[10px] py-[10px]',
  search:
    'mb-[14px] rounded-xl border border-[#E7E8DF] bg-white p-3 font-manrope text-[12px] text-[#203E35]',
  hero: 'h-[300px] overflow-hidden rounded-[19px] bg-[#203E35]',
  heroImage: 'absolute left-0 top-0 h-full w-full',
  heroShade: 'absolute bottom-0 left-0 right-0 top-0 bg-[#142D2340]',
  heroTop: 'p-4',
  badge: 'self-start rounded-[15px] bg-[#F6F2E5] px-[11px] py-[6px]',
  heroBody: 'mt-auto bg-[#183326CF] p-[18px]',
  heroTitle: 'font-garamond text-[32px] leading-[33px] text-[#FFFCF0]',
  heroDescription: 'mb-[13px] mt-[7px] font-manrope text-[10px] leading-4 text-[#E4E7D6]',
  heroLink: 'font-manrope-semibold text-[10px] text-[#E5EBC2]',
  quiet: 'mt-[19px] flex-row items-center gap-[13px] rounded-2xl bg-[#EAF0DF] p-[17px]',
  section: 'mb-[15px] mt-[26px]',
  card: 'mb-4 overflow-hidden rounded-[17px] border border-[#EDEEE6] bg-[#FFFDF9]',
  imageWrap: 'h-[183px] bg-[#E6E5DA]',
  cardImage: 'h-full w-full',
  imageTop: 'absolute left-[10px] right-[10px] top-[10px]',
  cardBody: 'p-[14px]',
  cardTitle: 'mb-[5px] mt-2 font-garamond text-[25px] text-[#203E35]',
  tag: 'self-start rounded-[5px] bg-[#F0F0E8] px-[7px] py-1',
  save: 'min-h-[35px] flex-row items-center justify-center gap-[5px] rounded-[20px] bg-[#203E35] px-[13px]',
  saveText: 'font-manrope-semibold text-[9px] text-white',
  grid: 'flex-row flex-wrap gap-3',
  compact: 'min-w-[125px] grow basis-[46%]',
  compactImage: 'h-[127px]',
  empty: 'items-center gap-[10px] p-[30px]',
} as const;
